version: '3.8'

services:
  nest-app-personnel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-personnel
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/human_resources_db 
      JWT_SECRET: superSecretKeyForJWT
      JWT_EXPIRES_IN: 1h
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network 
    restart: unless-stopped

volumes:
  mongo_data: 

networks:
  app_network:
    driver: bridge